<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Asynchronous JavaScript</title>
</head>
<body>
    <h1>Asynchronous JavaScript</h1>
    <script>
/* How it work? a simulation 
- we geta bunch of recipe IDs from a server, then base on that, we select a recipe and then
- we get that recipe from the server after that
1. we create the first setTimeout() with recipeID, then log()
2. we create the 2nd setTimeout() that recieves an argument (id)
    -has an object {recipe} and log
    -the argument we pass is recipeID
3. we create the 3rd setTimeout()
    - also reciv an argument (publisher) 
    - we pass the recipe.publisher 
3. 

And this is CALLBACK HELL. That is why in ES6 promises was created
when using asynchrounous JS
*/
// function getRecipe() {
//     setTimeout(() => {
//         const recipeID = [523, 883, 432, 974];
//         console.log(recipeID);

//         setTimeout(id => {
//             const recipe = {title: 'Fresh tomato pasta', publisher: 'Jonas'};
//             console.log(`${id}: ${recipe.title}`);

//             setTimeout(publisher => {
//                 const recipe2 = {title: 'Italian Pizza', publisher: 'Jonas'};
//                 console.log(recipe);
//             }, 1500, recipe.publisher);

//         }, 1500, recipeID[2]);

//     }, 1500);
// }
// getRecipe();




/* PROMISE 
1. 1st part to redo the 1st part of traditional callback hell above
   - promise take 2 argument resolve and reject 
   - if succesful the resolved will call and if not the reject
2. resolve - returns a value
3. so the setTimeout daw is impossible to failed kaya hindi natin tatawagin ung reject()
4. now that the 1st promise is done it only simply store the value to getIDs
5. All PROMISE() object inherits then() and catch() method
6. then() method allow us to add an event handler for the case that the promise
   - is fulfilled -- which means merong result
7. read the comment in 2ndA below - it explains the then() method
8. read 2ndB - it xplains catch() 
9. const getIDs - is not a function becoz we dont need to pass any data
10. const getRecipe is a function becoz we need to pass the recipe ID. to the promise
11. const getRelated = a recipe which is related to the author 
12. ang teknik, parang kada promise() my isang then() for them.
*/

    ////1st --------------- 1st Promise
        const getIDs = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve([523, 883, 432, 974]);
            }, 1500);
        });
///////--------------------


        //gets mo? ako gets ko. 
        //a function that reciv recipe ID
        //this is the 2nd setTimeout() above -converted in PROMISE()
        const getRecipe = recID => {
            return new Promise((resolve, reject) => {
                setTimeout(ID => {
                    const recipe = {title: 'Fresh tomato pasta', publisher: 'Jonas'};
                    resolve(`${ID}: ${recipe.title}`);
                }, 1500, recID);
            });
        };

        //the argument passed on setTimeout(cb,fn,time,argument) 
        // cb to argument - is the value we will pass for this promise
        // what? tangina anganda  ng explainiation mo ser!
        const getRelated = publisher => {
            return new Promise((resolve, reject) => {
                setTimeout(pub => {
                    const recipe = {title: 'Italian Pizza', publisher: 'Jonas'};
                    resolve(`${pub}: ${recipe.title}`);
                }, 1500, publisher);
            });
        };


//2ndA --------------------
// what we do here is to pass a callback() which will hanlde what we do
//in case the promise was successful
//the callback here can take an argument - hindi nya sinabi kung ilan
// the argument here will be the result of our 1st promise we created above, so in that case the array[]
// chaining -

        //this is handling the 1st promise above
    //     getIDs
    //     .then(IDs => {
    //         console.log(IDs);

    //         //chaining - we can return a promise from this method here
    //         // then it will simply add new promise (1A) to then() method below -
    //         //getRecipe 2A
    //         return getRecipe(IDs[2]); // this will return a promise 
    //     })

    //     //this will handle the 2nd promise above
    //     //1A new promise then() 
    //     //this will hanlde the result of getRecipe()2A promise above
    //     //this will use the 2nd setTimeout() above.
    //     // ung recipe argument is from the 1st then() result
        
    //     .then(recipe => {
    //         console.log(recipe);
    //         return getRelated('Jonas Schmedtmann');
    //     })

        
    //     //this will handle 3rd promise above 
    //     .then(recipe => {
    //         console.log(recipe);
    //     })

    // //2ndB--explaining the catch me
    // //catch method will allow us to add event handler for the case that a promise gets rejected
    // // so in this case console.log() error
    //     .catch(error => {
    //         console.log('Error!!');
    //     });

//// --------- ES8 or ES2017 -- Async / Await

//1. async function 
//2. call it getrecipeAW() below the async function
//we just need to wait (await) to the promise above eg(getIDs) to get result of success.
//then we can then use that value 
//await can only be use inside the async function()
//async function()  - it runs in the background 

        //a function mean asynchronous function
        //the one that keep running on the background
        async function getRecipesAW() {

            //kapag daw nasa await na, mag stop daw from executing, until ung promise sa taas mafulfill nya na success
            // so in this case we will get the IDs promise
            // so the value daw ng await expression is the resolve value of the promise
            // which we assigned to const IDs
            const IDs = await getIDs;
            console.log(IDs);

            //getRecipe(IDs[2]) we await that promise to finish
            //and after it finishes we can then log the recipe
            const recipe = await getRecipe(IDs[2]);
            console.log(recipe);



            const related = await getRelated('Jonas Schmedtmann');
            console.log(related);

            //not necessary
            //if we want to return a value from async function
            //we then put this return
            return recipe;
        }

        // kaya ganto daw - ung getRecipesAW() daw return a recipe (dba?) 
        // so nireturn nya recipe. meron din itong promise. so kada promise my inheritance ng then() and catch()
        // so kaya nagawa natin gamitan pa ng then dito() get mopa ? kaya pa?
    
        getRecipesAW().then(result => console.log(`${result} is the best ever!`));

    </script>
</body>
</html>